In [ ]:
import pandas as pd
import seaborn as sb
import matplotlib.pylab as plt


data_1 = pd.read_excel("customer_5000_rows_with_capital.xlsx")
data_2 = pd.read_csv("SuperMarket_Analysis_Corrected.csv")

:

In [177]:
data_2.columns

Index(['Invoice ID', 'City', 'Product line', 'Unit price', 'Quantity', 'Sales',
       'Date', 'Time'],
      dtype='object')

In [178]:
data_1["Sales"] = data_1["Quantity"] * data_1["UnitPrice"]
data_1.columns

Index(['InvoiceNo', 'Description', 'Quantity', 'InvoiceDate', 'UnitPrice',
       'CapitalCity', 'Sales'],
      dtype='object')

In [179]:
data_1

,InvoiceNo,Description,Quantity,InvoiceDate,UnitPrice,CapitalCity,Sales
0,536365,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,London,15.30
1,536365,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,London,20.34
2,536365,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,London,22.00
3,536365,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,London,20.34
4,536365,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,London,20.34
...,...,...,...,...,...,...,...
4994,536836,LARGE CAKE STAND HANGING STRAWBERY,2,2010-12-02 18:08:00,9.95,London,19.90
4995,536836,RED RETROSPOT CAKE STAND,2,2010-12-02 18:08:00,10.95,London,21.90
4996,536836,RED RETROSPOT SUGAR JAM BOWL,2,2010-12-02 18:08:00,2.55,London,5.10
4997,536836,RED RETROSPOT BUTTER DISH,3,2010-12-02 18:08:00,4.95,London,14.85
4998,536836,LARGE POPCORN HOLDER,2,2010-12-02 18:08:00,1.65,London,3.30

In [180]:
data_1["InvoiceDate"] = pd.to_datetime(data_1["InvoiceDate"])
data_1['Date'] = data_1['InvoiceDate'].dt.strftime('%Y-%m-%d')
data_1["Time"] = data_1["InvoiceDate"].dt.time
data_2["Date"] = pd.to_datetime(data_2["Date"])
data_2['Date'] = data_2['Date'].dt.strftime('%Y-%m-%d')
data_2['Time'] = pd.to_datetime(data_2['Time']).dt.strftime('%H:%M:%S')

C:\Users\Top 10\AppData\Local\Temp\ipykernel_15808\3789785167.py:6: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  data_2['Time'] = pd.to_datetime(data_2['Time']).dt.strftime('%H:%M:%S')

In [181]:
data_cleaned_1 = data_1.drop('InvoiceDate',axis=1)
data_cleaned_1

,InvoiceNo,Description,Quantity,UnitPrice,CapitalCity,Sales,Date,Time
0,536365,WHITE HANGING HEART T-LIGHT HOLDER,6,2.55,London,15.30,2010-12-01,08:26:00
1,536365,WHITE METAL LANTERN,6,3.39,London,20.34,2010-12-01,08:26:00
2,536365,CREAM CUPID HEARTS COAT HANGER,8,2.75,London,22.00,2010-12-01,08:26:00
3,536365,KNITTED UNION FLAG HOT WATER BOTTLE,6,3.39,London,20.34,2010-12-01,08:26:00
4,536365,RED WOOLLY HOTTIE WHITE HEART.,6,3.39,London,20.34,2010-12-01,08:26:00
...,...,...,...,...,...,...,...,...
4994,536836,LARGE CAKE STAND HANGING STRAWBERY,2,9.95,London,19.90,2010-12-02,18:08:00
4995,536836,RED RETROSPOT CAKE STAND,2,10.95,London,21.90,2010-12-02,18:08:00
4996,536836,RED RETROSPOT SUGAR JAM BOWL,2,2.55,London,5.10,2010-12-02,18:08:00
4997,536836,RED RETROSPOT BUTTER DISH,3,4.95,London,14.85,2010-12-02,18:08:00
4998,536836,LARGE POPCORN HOLDER,2,1.65,London,3.30,2010-12-02,18:08:00

In [182]:
data_cleaned_2 = data_2
data_cleaned_2

,Invoice ID,City,Product line,Unit price,Quantity,Sales,Date,Time
0,750-67-8428,Berlin,Health and beauty,74.69,7,548.9715,2019-01-05,13:08:00
1,226-31-3081,Madrid,Electronic accessories,15.28,5,80.2200,2019-03-08,10:29:00
2,631-41-3108,Berlin,Home and lifestyle,46.33,7,340.5255,2019-03-03,13:23:00
3,123-19-1176,Berlin,Health and beauty,58.22,8,489.0480,2019-01-27,20:33:00
4,373-73-7910,Berlin,Sports and travel,86.31,7,634.3785,2019-02-08,10:37:00
...,...,...,...,...,...,...,...,...
995,233-67-5758,Madrid,Health and beauty,40.35,1,42.3675,2019-01-29,13:46:00
996,303-96-2227,Paris,Home and lifestyle,97.38,10,1022.4900,2019-03-02,17:16:00
997,727-02-1313,Berlin,Food and beverages,31.84,1,33.4320,2019-02-09,13:22:00
998,347-56-2442,Berlin,Home and lifestyle,65.82,1,69.1110,2019-02-22,15:33:00
999,849-09-3807,Berlin,Fashion accessories,88.34,7,649.2990,2019-02-18,13:28:00

In [183]:
data_cleaned_1.rename(columns={'InvoiceNo': 'Item_id','Description':'Product','InvoiceDate':'Date','UnitPrice':'Unit_Price','CapitalCity':'City'},inplace=True)
data_cleaned_2.rename(columns={'Invoice ID':'Item_id','City':'City','Product line':'Product','Unit price':'Unit_Price',},inplace=True)

In [184]:
data_cleaned_1.columns

Index(['Item_id', 'Product', 'Quantity', 'Unit_Price', 'City', 'Sales', 'Date',
       'Time'],
      dtype='object')

In [185]:
data_cleaned_2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Item_id     1000 non-null   object
 1   City        1000 non-null   object
 2   Product     1000 non-null   object
 3   Unit_Price  1000 non-null   float64
 4   Quantity    1000 non-null   int64
 5   Sales       1000 non-null   float64
 6   Date        1000 non-null   object
 7   Time        1000 non-null   object
dtypes: float64(2), int64(1), object(5)
memory usage: 62.6+ KB

In [186]:
data_concat = [data_cleaned_1, data_cleaned_2]
data_set = pd.concat(data_concat,ignore_index=True)
data_set

,Item_id,Product,Quantity,Unit_Price,City,Sales,Date,Time
0,536365,WHITE HANGING HEART T-LIGHT HOLDER,6,2.55,London,15.3000,2010-12-01,08:26:00
1,536365,WHITE METAL LANTERN,6,3.39,London,20.3400,2010-12-01,08:26:00
2,536365,CREAM CUPID HEARTS COAT HANGER,8,2.75,London,22.0000,2010-12-01,08:26:00
3,536365,KNITTED UNION FLAG HOT WATER BOTTLE,6,3.39,London,20.3400,2010-12-01,08:26:00
4,536365,RED WOOLLY HOTTIE WHITE HEART.,6,3.39,London,20.3400,2010-12-01,08:26:00
...,...,...,...,...,...,...,...,...
5994,233-67-5758,Health and beauty,1,40.35,Madrid,42.3675,2019-01-29,13:46:00
5995,303-96-2227,Home and lifestyle,10,97.38,Paris,1022.4900,2019-03-02,17:16:00
5996,727-02-1313,Food and beverages,1,31.84,Berlin,33.4320,2019-02-09,13:22:00
5997,347-56-2442,Home and lifestyle,1,65.82,Berlin,69.1110,2019-02-22,15:33:00
5998,849-09-3807,Fashion accessories,7,88.34,Berlin,649.2990,2019-02-18,13:28:00